"""Independent external-readonly reference services for Cognition System."""

from external_readonly.provider_adapter import (
    EXTERNAL_READONLY_ADAPTER_ALLOWED_OPERATIONS,
    EXTERNAL_READONLY_ADAPTER_ALLOWED_PROVIDER_FAMILIES,
    EXTERNAL_READONLY_ADAPTER_FAMILY_OPERATIONS,
    EXTERNAL_READONLY_ADAPTER_SLOT_STAGES,
    ExternalReadonlyAdapterProfile,
    ExternalReadonlyAdapterProjectionResult,
    ExternalReadonlyAdapterRecord,
    ExternalReadonlyAdapterRequest,
    external_readonly_adapter_projection_status_dict,
    project_external_readonly_adapter_records,
)
from external_readonly.governed_summary_facts import (
    EXTERNAL_READONLY_GOVERNED_SUMMARY_FACTS_POLICY_REF,
    build_external_readonly_governed_summary_facts,
    external_readonly_governed_summary_facts_status_dict,
)
from external_readonly.provider_registry import (
    EXTERNAL_READONLY_ADAPTER_ENTRY_STATUSES,
    EXTERNAL_READONLY_ADAPTER_REGISTRY_VERSION,
    EXTERNAL_READONLY_DEFAULT_ADAPTER_NAMES,
    ExternalReadonlyAdapterRegistry,
    ExternalReadonlyAdapterRegistryEntry,
    ExternalReadonlyAdapterRegistryReview,
    build_default_external_readonly_adapter_registry,
    build_external_readonly_adapter_registry,
    external_readonly_adapter_profile_from_registry_entry,
    external_readonly_adapter_registry_review_status_dict,
    external_readonly_adapter_registry_status_dict,
    review_external_readonly_adapter_registry_entry,
)
from external_readonly.url_fetch import (
    ExternalReadonlyEvidenceEnvelope,
    ExternalReadonlyHttpResponse,
    ExternalReadonlyHttpTransport,
    ExternalReadonlyNetworkGateView,
    ExternalReadonlyUrlFetchRequest,
    ExternalReadonlyUrlFetchResult,
    coerce_external_readonly_network_gate_view,
    external_readonly_evidence_envelope_status_dict,
    external_readonly_url_fetch_result_status_dict,
    run_external_readonly_url_fetch,
    urllib_external_readonly_https_get_transport,
)

__all__ = [
    "EXTERNAL_READONLY_ADAPTER_ENTRY_STATUSES",
    "EXTERNAL_READONLY_ADAPTER_REGISTRY_VERSION",
    "EXTERNAL_READONLY_ADAPTER_ALLOWED_OPERATIONS",
    "EXTERNAL_READONLY_ADAPTER_ALLOWED_PROVIDER_FAMILIES",
    "EXTERNAL_READONLY_ADAPTER_FAMILY_OPERATIONS",
    "EXTERNAL_READONLY_ADAPTER_SLOT_STAGES",
    "EXTERNAL_READONLY_GOVERNED_SUMMARY_FACTS_POLICY_REF",
    "EXTERNAL_READONLY_DEFAULT_ADAPTER_NAMES",
    "ExternalReadonlyAdapterProfile",
    "ExternalReadonlyAdapterProjectionResult",
    "ExternalReadonlyAdapterRecord",
    "ExternalReadonlyAdapterRegistry",
    "ExternalReadonlyAdapterRegistryEntry",
    "ExternalReadonlyAdapterRegistryReview",
    "ExternalReadonlyAdapterRequest",
    "ExternalReadonlyEvidenceEnvelope",
    "ExternalReadonlyHttpResponse",
    "ExternalReadonlyHttpTransport",
    "ExternalReadonlyNetworkGateView",
    "ExternalReadonlyUrlFetchRequest",
    "ExternalReadonlyUrlFetchResult",
    "build_default_external_readonly_adapter_registry",
    "build_external_readonly_governed_summary_facts",
    "build_external_readonly_adapter_registry",
    "coerce_external_readonly_network_gate_view",
    "external_readonly_adapter_profile_from_registry_entry",
    "external_readonly_adapter_projection_status_dict",
    "external_readonly_adapter_registry_review_status_dict",
    "external_readonly_adapter_registry_status_dict",
    "external_readonly_evidence_envelope_status_dict",
    "external_readonly_governed_summary_facts_status_dict",
    "external_readonly_url_fetch_result_status_dict",
    "project_external_readonly_adapter_records",
    "review_external_readonly_adapter_registry_entry",
    "run_external_readonly_url_fetch",
    "urllib_external_readonly_https_get_transport",
]
